### ISSUE TITLE
Issues resolving dependencies with version 0.2.1

### ISSUE THREAD

**Issue by javydreamercsw** [SurpSG/diff-coverage-maven-plugin#15]
Getting this error:

`The POM for com.github.form-com.diff-coverage-gradle:jacoco-filtering-extension:jar:0.9.0 is missing, no dependency information available`

**Comment by SurpSG** [comment]
I've tried to reproduce with a simple project in clean docker container(to make sure I have not some cached artifacts) but couldn't repoproduce.

```
# mvn clean diff-coverage:diffCoverage
...
Downloading from jitpack.io: https://jitpack.io/com/github/form-com/diff-coverage-gradle/jacoco-filtering-extension/0.9.0/jacoco-filtering-extension-0.9.0.jar
Downloaded from jitpack.io: https://jitpack.io/com/github/form-com/diff-coverage-gradle/jacoco-filtering-extension/0.9.0/jacoco-filtering-extension-0.9.0.jar (99 kB at 2.6 MB/s)
[INFO] diff content saved to '/tmp/proj/target/site/diff.patch'
[WARNING] Fail on violations: false. Found violations: 0.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.758 s
[INFO] Finished at: 2022-02-17T01:38:41+02:00
[INFO] ------------------------------------------------------------------------
```

Please, try to clean maven artifacts:
```bash
rm -rf ~/.m2/repository/com/github/form-com
rm -rf ~/.m2/repository/com/github/surpsg
```
and then
```bash
mvn clean diff-coverage:diffCoverage
```

If the issue still present then please provide your maven version and more details from your build log

**Comment by SurpSG** [comment]
Resolving the issue due to inactivity. If you have any updates then feel free to reopen it with additional info

**Comment by javydreamercsw** [comment]
Somehow I missed this reply. We use Maven 3.8.6 from their Docker image (3.8.6-jdk-8). What other type of details are you looking for?

**Comment by SurpSG** [comment]
Could you confirm that the issue is present after [suggestions](https://github.com/SurpSG/diff-coverage-maven-plugin/issues/15#issuecomment-1042421521)?
