### ISSUE TITLE
how to exclude certain classes and packages from coverage check report

### ISSUE THREAD

**Issue by eMe-404** [SurpSG/diff-coverage-maven-plugin#16]
is there any way we can exclude certain classes and packages from coverage check report, we try to setup this exclusion in jacoco configuration but it not works

**Comment by SurpSG** [comment]
Hi @eMe-404 
No, Diff Coverage doesn't support exclusion.

Could you please describe your case? Why you want to exclude packages or classes?

**Comment by eMe-404** [comment]
hi @SurpSG the use case same as Jacoco exclusion

Generally, the candidates for exclusion can be configuration classes, POJOs, DTOs, as well as generated byte code. These carry no specific business logic, and it could be useful to exclude them from the reports in order to provide a better view of the test coverage.

**Comment by SurpSG** [comment]
> POJOs, DTOs
Do you use Lombok?

> as well as generated byte code
Usually, standart JaCoCo filters omit generated bytecode preaty well(this filters are inherited by Diff-Coverage).

Just trying to understand whether we really need to implement such feature. 
Sometimes we disable Diff-Coverage check in CI if there are some reasons. For example, you have switch-case with enumerated all Enum values. It's impossible to cover default branch in the switch-case.

**Comment by eMe-404** [comment]
I think rather then disabling the check in CI it is better to have this extensibility, I know Diff-Coverage rely on Jacoco so just thinking whether we can also inherit Jacoco exclusion to have better consistency? 

my case is: I already have some exclusion for `Jacoco`(as below demo config shows) and after adding `Diff-Coverage` there is inconsistency between the report generated by them

![image](https://user-images.githubusercontent.com/31622637/183437583-e072ae2a-22ae-46bc-bf72-11f8bb1220c5.png)

**Comment by SurpSG** [comment]
Ok, makes sense, thank you.

I'll try to implement and release it this week

**Comment by eMe-404** [comment]
thanks for quick response, I also raise a PR for this feature, can you please review it?

**Comment by karimbounekhla** [comment]
@SurpSG Do you have an ETA on this release? Thank you

**Comment by SurpSG** [comment]
@karimbounekhla I've faced with some issues after adding these changes. I need about 2-3 weeks. When I solve the issues I'll relese asap

**Comment by karimbounekhla** [comment]
@SurpSG Sounds good, appreciate it!

**Comment by SurpSG** [comment]
It has been released [0.3.0](https://github.com/SurpSG/diff-coverage-maven-plugin/releases/tag/0.3.0) :tada:
