### ISSUE TITLE
Multi-module report generation broken in 0.3.0 (git branch diff)

### ISSUE THREAD

**Issue by karimbounekhla** [SurpSG/diff-coverage-maven-plugin#25]
When I upgrade plugin to 0.3.0 (upgrade only, no other changes to POM or plugin configuration included/excluded classes), the plugin is no longer picking up any diff between current branch and other branch.

`diff.patch` is empty file

When I use 0.2.1, the diff is picked up correctly.

**Comment by SurpSG** [comment]
Hi @karimbounekhla 
Have you staged the changes?
```bash
git add .
```


If the changes are not staged then it will not be included into diff generated by embedded git.

**Comment by SurpSG** [comment]
I've created a test PR https://github.com/SurpSG/diff-coverage-maven-plugin/pull/26/files
(diff-coverage v0.3.0)

You could observe [artifacts](https://github.com/SurpSG/diff-coverage-maven-plugin/suites/8250486656/artifacts/360628640) in the related [build](https://github.com/SurpSG/diff-coverage-maven-plugin/actions/runs/3038771044). The diff was generated successefully

**Comment by karimbounekhla** [comment]
I will test now, however in `0.2.1`, it was picking up uncommitted changes as well so I assume functionality should be the same.

Per the comment in the README
```
                    <!-- branch, revision or tag -->
                    <git>HEAD</git> <!-- compares current HEAD and all uncommited with this <git> -->
```

**Comment by karimbounekhla** [comment]
@SurpSG Thanks, it seems to work with staged files. I guess that's fine :)

**Comment by SurpSG** [comment]
The behavior was changed unintentionally. It brings minor confuses when you run the plugin locally. From the other side we have important bug [fix](https://github.com/form-com/diff-coverage-gradle/issues/34)
