### ISSUE TITLE
Diff coverage report mismatch for kotlin code

### ISSUE THREAD

**Issue by mkc450** [SurpSG/diff-coverage-maven-plugin#33]
I integrated diff coverage tool to our applications. 

Recently I observed the following issue. 

- Made a single line change in the kotlin code. But in the report it shows other methods of same class as well even though there is no code change. 
- Ran the plugin with debug mode, the diff it reads is correct but the report generated is not correct. Again on looking into the class file it shows the diff currently. Only the methods which it selected corresponding to the diff code is wrong.
- Is there any known issue related to kotlin. 

@SurpSG Can you help us in fixing the issue. 

Do let me know if you need any more information regarding the same.

**Comment by mkc450** [comment]
Hey

I think its the issue with configuration. I solved it by restricting only minLines instead of minInstructions.

**Comment by SurpSG** [comment]
Hi @mkc450 
If you provide more context then I could help. It would be nice to have a sample project where I can reproduce the issue.
