### ISSUE TITLE
Configure classesDirs and sourceDirs 

### ISSUE THREAD

**Issue by mkc450** [SurpSG/diff-coverage-maven-plugin#34]
Is there a way to configure classesDirs and sourceDirs in maven plugin similar to gradle plugin. As I can see from the code that reactorProjects is used get classesDirs. 

I use a multi module maven pom, I added the diffCoverage goal to some of the child modules. But on debugging I realized that at each submodules it takes all the modules using reactorProjects and runs for everything. Can't we run this plugin at required submodules only. If yes can you please explain the way to do it. Thanks

**Comment by SurpSG** [comment]
Unfortunatelly, Maven is much less flexible comparing to Gradle. Thats why I can suggest far from perfect solution, but it should work for you:
1. Create a separate report module that depends on submodules you want to build report for.
2. Configure classes using include/exclude. 
3. Configure exec files using dataFileIncludes/dataFileExcludes.

Note: we don't need to configure sources separately(Jacoco engine skip sources that doesn't have corresponding class files)

Here example from integration tests: [multi-module-reports-generation-check](https://github.com/SurpSG/diff-coverage-maven-plugin/blob/master/src/it/multi-module-reports-generation-check/report/pom.xml)

If you have additional questions or you have some issues with the suggested approach then feel free to ask.

**Comment by mkc450** [comment]
@SurpSG This worked for me.
