### ISSUE TITLE
Support for maven 3.9

### ISSUE THREAD

**Issue by ulejon** [SurpSG/diff-coverage-maven-plugin#35]
Hi,

Are you planning on supporting maven 3.9?
Copied from Maven 3.9 release notes:
"Maven 2.x was auto-injecting an ancient version of plexus-utils dependency into the plugin classpath, and Maven 3.x continued doing this to preserve backward compatibility. Starting with Maven 3.9, it does not happen anymore. This change may lead to plugin breakage. The fix for affected plugin maintainers is to explicitly declare a dependency on plexus-utils. The workaround for affected plugin users is to add this dependency to plugin dependencies until issue is fixed by the affected plugin maintainer"

**Comment by SurpSG** [comment]
Fixed in release (0.3.2)[https://github.com/SurpSG/diff-coverage-maven-plugin/releases/tag/0.3.2]
