### ISSUE TITLE
Coverage 0% in modules after modified module

### ISSUE THREAD

**Issue by SilvaUnCompte** [SurpSG/diff-coverage-maven-plugin#39]
Hi, I try to make it work diff-coverage in a multi module projet but it seems to have an issus. (May be i'm just dumb)

First modules haven't any change and pass the test. First module with a modification work fine but every futher modules (in execution order) return 0% coverage although they have no change.

If I try to modify an other module instead, same issus with this module.
It's an internal issus? Or I need extra neurons?

Thanks in advance.

NB: JaCoCo seems to work fine.

**Comment by SurpSG** [comment]
Hi @SilvaUnCompte 

Don't Be So Hard On Yourself :)

Please, provide more context, so I could help you.
* Ideally, provide a sample project if possible.
* Or provide your diff coverage plugin configuration.

Also, check a patch file `target/site/diff.patch` generated by the plugin. Is it generated properly?

Thanks!

**Comment by SilvaUnCompte** [comment]
Don't worry, I'm kidding. My neurons are fine (I think... I hope :))

I can't give the project, but there's the configuration:

In pluginManagement:
`<plugin>
    <groupId>com.github.surpsg</groupId>
    <artifactId>diff-coverage-maven-plugin</artifactId>
    <version>0.3.1</version>
    <configuration>
        <diffSource>
            <file>${project.build.outputDirectory}/diff.patch</file>
        </diffSource>
        <violations>
            <failOnViolation>false</failOnViolation>
            <minCoverage>0.85</minCoverage>
        </violations>
        <dataFileIncludes>${sonar.jacoco.reportPath}</dataFileIncludes>
    </configuration>
</plugin>`

In plugins:
`<plugin>
    <groupId>com.github.surpsg</groupId>
    <artifactId>diff-coverage-maven-plugin</artifactId>
</plugin>`

Each diff.patch in the modules contains all project modifications.

**Comment by SilvaUnCompte** [comment]
Only apply in root pom. It seems run in each module, isn't it ?

**Comment by SurpSG** [comment]
Hi @SilvaUnCompte 
Thank you for the update
