### ISSUE TITLE
the coverage of diff code is 0

### ISSUE THREAD

**Issue by eamon-t-2023** [SurpSG/diff-coverage-maven-plugin#42]
Hi @SurpSG , after I **added this plugin to my demo single module** project like below: 

```
<plugin>
    <groupId>com.github.surpsg</groupId>
    <artifactId>diff-coverage-maven-plugin</artifactId>
    <version>0.3.2</version>
    <configuration>
        <diffSource>
            <git>master</git>
        </diffSource>
        <dataFileIncludes>target/*.exec</dataFileIncludes>
    </configuration>
    <executions>
        <execution>
            <phase>prepare-package</phase>
            <goals>
                <goal>diffCoverage</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
then **I created a new branch**.

then **added a minus func** in Math.class and the corresponding **unit test case**  in MatchTest.class of this new branch
```
public int minus(int num1, int num2) {
        return num1 - num2;
    }
```

```
    @Test
    void minus() {
        Math math = new Math();
        assertEquals(0, math.minus(1, 1));
    }
```

Finally, i packaged my project. I got the diff report like this:
<img width="884" alt="image" src="https://github.com/SurpSG/diff-coverage-maven-plugin/assets/129372987/c78ce394-58bf-441b-8b59-9fb60fefaee5">

I am not sure why the coverage is 0, I mean, I have added the test case of the diff new function, the coverage should be 100% right?

<img width="521" alt="image" src="https://github.com/SurpSG/diff-coverage-maven-plugin/assets/129372987/0c795291-848d-41ce-997f-798ddf7bc143">

another question is that, the minus function is new added, it should be green right? why here is red. I think because this is red, so the coverage is 0.

Thanks for your kindly help

**Comment by eamon-t-2023** [comment]
solved this after i switch from Junit5 to Junit4.
can this plugin support Junit5?

**Comment by SurpSG** [comment]
Hi @eamon-t-2023 

The plugin should work for both junit4 and junit5 or any another testing framework.
Seems, swithching to junit4 solves some another issue in your project. I don't recommend using legacy junit4.
Let's find out what went wrong in your project using junit5. 
I could help if you provide a sample project in which I can reproduce the issue. Could you provide the sample project?

**Comment by SurpSG** [comment]
> another question is that, the minus function is new added, it should be green right? why here is red. I think because this is red, so the coverage is 0.

Yes, red means no coverage. Green - the code is covered.

For some reason no coverage data was collected.

**Comment by eamon-t-2023** [comment]
thanks @SurpSG , you are right, your plugin also support Junit5. I think the issue must related to the jacoco plugin configuration. although i still don't know the root cause. once i located, i will update this issue.
